destinationServer: ''
argoNamespace: ''
argoProject: ''

labels:
  env: dev
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/aleksmeshr/eks-cdk-example
    targetRevision: main
  env: dev
  clusterName: mycluster1
  blueprint: 'cdk'
  karpenterInstanceProfile:
  ingress:
    type: 'alb' # nginx | alb
    host: # empty or your domain like dev.example.com
