apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  destination:
    namespace: app1
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
    path: apps/app1/dev
    helm:
      values: |
        {{- toYaml .Values | nindent 8 }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
